package cn.sharesdk.testgreendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.sharesdk.testgreendao.sqlite.AreaInfo;
import cn.sharesdk.testgreendao.sqlite.DeviceInfo;
import cn.sharesdk.testgreendao.sqlite.FlagInfo;
import cn.sharesdk.testgreendao.sqlite.TabInfo;

import cn.sharesdk.testgreendao.greendao.AreaInfoDao;
import cn.sharesdk.testgreendao.greendao.DeviceInfoDao;
import cn.sharesdk.testgreendao.greendao.FlagInfoDao;
import cn.sharesdk.testgreendao.greendao.TabInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaInfoDaoConfig;
    private final DaoConfig deviceInfoDaoConfig;
    private final DaoConfig flagInfoDaoConfig;
    private final DaoConfig tabInfoDaoConfig;

    private final AreaInfoDao areaInfoDao;
    private final DeviceInfoDao deviceInfoDao;
    private final FlagInfoDao flagInfoDao;
    private final TabInfoDao tabInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaInfoDaoConfig = daoConfigMap.get(AreaInfoDao.class).clone();
        areaInfoDaoConfig.initIdentityScope(type);

        deviceInfoDaoConfig = daoConfigMap.get(DeviceInfoDao.class).clone();
        deviceInfoDaoConfig.initIdentityScope(type);

        flagInfoDaoConfig = daoConfigMap.get(FlagInfoDao.class).clone();
        flagInfoDaoConfig.initIdentityScope(type);

        tabInfoDaoConfig = daoConfigMap.get(TabInfoDao.class).clone();
        tabInfoDaoConfig.initIdentityScope(type);

        areaInfoDao = new AreaInfoDao(areaInfoDaoConfig, this);
        deviceInfoDao = new DeviceInfoDao(deviceInfoDaoConfig, this);
        flagInfoDao = new FlagInfoDao(flagInfoDaoConfig, this);
        tabInfoDao = new TabInfoDao(tabInfoDaoConfig, this);

        registerDao(AreaInfo.class, areaInfoDao);
        registerDao(DeviceInfo.class, deviceInfoDao);
        registerDao(FlagInfo.class, flagInfoDao);
        registerDao(TabInfo.class, tabInfoDao);
    }
    
    public void clear() {
        areaInfoDaoConfig.clearIdentityScope();
        deviceInfoDaoConfig.clearIdentityScope();
        flagInfoDaoConfig.clearIdentityScope();
        tabInfoDaoConfig.clearIdentityScope();
    }

    public AreaInfoDao getAreaInfoDao() {
        return areaInfoDao;
    }

    public DeviceInfoDao getDeviceInfoDao() {
        return deviceInfoDao;
    }

    public FlagInfoDao getFlagInfoDao() {
        return flagInfoDao;
    }

    public TabInfoDao getTabInfoDao() {
        return tabInfoDao;
    }

}
